In [1]:
import pandas as pd

In [31]:
cluster17 = pd.read_csv("cluster17.csv")
final_data_regata = pd.read_csv("final_data_regata.csv", low_memory=False)

In [32]:
final_data_regata = final_data_regata.iloc[:, 1:]
print(final_data_regata.shape)
final_data_regata.head()

(92878, 15)

,ID Resultado,ID Competidor,Nome Competidor,ID Competição,Classe Vela,Pontuação Regata,Descarte,Flotilha,Posição Geral,Punição,Pontuação Total,Nett,Nome Competição,Regata,Nacionalidade
0,NaN,NaN,MINA MOBEKK,NaN,IQFOIL FEM.,15.0,0,NaN,1,0,207,116,European Championship 2023,1Q,NaN
1,NaN,NaN,MINA MOBEKK,NaN,IQFOIL FEM.,2.0,0,NaN,1,0,207,116,European Championship 2023,2Q,NaN
2,NaN,NaN,MINA MOBEKK,NaN,IQFOIL FEM.,6.0,0,NaN,1,0,207,116,European Championship 2023,3Q,NaN
3,NaN,NaN,MINA MOBEKK,NaN,IQFOIL FEM.,3.0,0,NaN,1,0,207,116,European Championship 2023,4Q,NaN
4,NaN,NaN,MINA MOBEKK,NaN,IQFOIL FEM.,3.0,0,NaN,1,0,207,116,European Championship 2023,5Q,NaN

In [33]:
cluster17["Classe Vela"] = cluster17["Classe Vela"].str.upper()
print(cluster17.shape)
cluster17.head()

(13329, 15)

,ID Resultado,ID Competidor,Nome Competidor,ID Competição,Classe Vela,Pontuação Regata,Descarte,Flotilha,Posição Geral,Punição,Pontuação Total,Nett,Nome Competição,Regata,Nacionalidade
0,-,-,ANNE-MARIE RINDOM,-,ILCA 6,1.0,0,Gold,1,0,88.0,40.0,World Championship 2015,Q1,DEN
1,-,-,MARIT BOUWMEESTER,-,ILCA 6,2.0,0,Gold,2,0,101.0,40.0,World Championship 2015,Q1,NED
2,-,-,EVI VAN ACKER,-,ILCA 6,2.0,0,Gold,3,0,120.0,44.0,World Championship 2015,Q1,BEL
3,-,-,TUULA TENKANEN,-,ILCA 6,12.0,1,Gold,4,0,73.0,49.0,World Championship 2015,Q1,FIN
4,-,-,JOSEFIN OLSSON,-,ILCA 6,20.0,1,Gold,5,0,96.0,53.0,World Championship 2015,Q1,SWE

In [34]:
dF_final = pd.concat([final_data_regata, cluster17])

In [35]:
dF_final.head()

,ID Resultado,ID Competidor,Nome Competidor,ID Competição,Classe Vela,Pontuação Regata,Descarte,Flotilha,Posição Geral,Punição,Pontuação Total,Nett,Nome Competição,Regata,Nacionalidade
0,NaN,NaN,MINA MOBEKK,NaN,IQFOIL FEM.,15.0,0,NaN,1,0,207,116,European Championship 2023,1Q,NaN
1,NaN,NaN,MINA MOBEKK,NaN,IQFOIL FEM.,2.0,0,NaN,1,0,207,116,European Championship 2023,2Q,NaN
2,NaN,NaN,MINA MOBEKK,NaN,IQFOIL FEM.,6.0,0,NaN,1,0,207,116,European Championship 2023,3Q,NaN
3,NaN,NaN,MINA MOBEKK,NaN,IQFOIL FEM.,3.0,0,NaN,1,0,207,116,European Championship 2023,4Q,NaN
4,NaN,NaN,MINA MOBEKK,NaN,IQFOIL FEM.,3.0,0,NaN,1,0,207,116,European Championship 2023,5Q,NaN

In [36]:
dF_final.to_csv("final_data_regata.csv", index=False)